services:
 ###################################### TODO APP ######################################
 #---------- BE ----------#
  todo-be:
    build:
      context: ./todo_app-be
      dockerfile: Dockerfile
    container_name: todo-be
    volumes:
      - ./todo_app-be/todo.ini:/usr/local/etc/php/conf.d/todo.ini
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - todo-mysql
      - todo-redis
    networks:
      - todo-network
    # environment:
    #   DB_CONNECTION: mysql
    #   DB_HOST: todo-mysql
    #   DB_PORT: 3306
    #   DB_DATABASE: todo
    #   DB_USERNAME: todo
    #   DB_PASSWORD: password
  
  #---------- DB ----------#
  todo-mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: todo
      MYSQL_USER: 'todo'
      MYSQL_PASSWORD: 'password'
      LANG: C.UTF-8
    command: --default-authentication-plugin=mysql_native_password --tls-version='' --bind-address=0.0.0.0 --mysqlx=0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - todo-network

  #---------- Redis ----------#
  todo-redis:
    image: "redis:7-alpine"
    container_name: todo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - todo-network


#---------- FE ----------#
  todo-fe:
    build:
      context: ./todo_app-fe
      dockerfile: Dockerfile
    container_name: todo-fe
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - fe-data:/app/node_modules
    networks:
      - todo-network

#---------- Nginx ----------#
  todo-nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/be.conf:/etc/nginx/conf.d/be.conf
      - ./nginx/fe.conf:/etc/nginx/conf.d/fe.conf
    depends_on:
      - todo-be
      - todo-fe
    networks:
      - todo-network

#---------- Volumes ----------#
volumes:
  mysql-data: 
    driver: local
  redis-data:
    driver: local
  be-data: 
    driver: local
  fe-data:
    driver: local

#---------- Networks ----------#
networks:
  todo-network:
    driver: bridge


      
